services: 

  server: 
    build: 
      context: "."
      dockerfile: ./server/Dockerfile
    container_name: note_script-app

    environment: 
      NODE_ENV: production
    ports: 
      - "5000:${PORT}"
    restart: always
    volumes: 
      - /Desktop/Users/adam/desktop/Code/Apps/Docker_example
version: "3.9"

        