version: "3.9"

services:
  app-dev:
    build: 
      context: .
      target: dev
    container_name: note_script-app-dev
    restart: always
    volumes: 
      - .:/app
    ports:
      - "5000:5000"
      - "3000:3000"
    depends_on:
      - note_script-dev
    environment:
      - MONGODB_URI=mongodb+srv://adam:notescript@cluster0.fepd2.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

    
  note_script-dev:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017 

