services: 
  # mongo: 
  #   container_name: mongo
  #   environment: 
  #     - "MONGODB_URI=mongodb+srv://adam:notescript@cluster0.fepd2.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  #   image: mongo
  #   ports: 
  #     - "27017:27017"
  # redis-server:
  #   container_name: redis
  #   image: "redis"
  #   ports: 
  #     - "6379:6379"
  server: 
    build: 
      context: "."
      dockerfile: ./server/Dockerfile
    container_name: note_script-app
    depends_on: 
      - mongo
    environment: 
      NODE_ENV: production
    ports: 
      - "5000:5000"
    ports: 
      - ${PORT}
    restart: always
    volumes: 
      - /Desktop/Users/adam/desktop/Code/Apps/Docker_example
version: "3.9"

  #  mongo-express:
  #    image: mongo-express
  #    restart: always 
  #    depends_on:
  #     - mongo
  #    ports:
  #      - "8080:8081"

  #  client:
  #     restart: always
  #     build:
  #       context: ./client
  #       dockerfile: Dockerfile
  #     ports:
  #       - 3000:3000
        