version: '3.9'

services:
   library-api:
     restart: always
     build:
       context: ./server
       dockerfile: Dockerfile.dev
     container_name: new_music_mern
     volumes:
      - /app/node_modules
     ports:
       - 5000:5000
     depends_on:
      - mongo
     environment:
       NODE_ENV: development


   mongo:
     container_name: mongo
     image: mongo
     ports:
      - "27017:27017"
   mongo-express:
     image: mongo-express
     restart: always
     depends_on:
      - mongo
     ports:
       - "8080:8081"

   client:
      restart: always
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - 3000:3000
        