version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8080:8081"
  client:
      restart: always
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - 3000:3000
        