name: Docker Image Build

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build front end Docker Image
      run: docker build ./client
      
    - name: Build backend end Docker Image
      run: docker build ./server
