name: Docker Image Build

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build front end Docker Image
      run: docker-compose -f "docker-compose.yml" up -d --build
